#!/usr/bin/env python3
import sys
import helpers
import os
import nltk
from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        print("Usage: ./tweets @screenName")
        exit(1)
    screen_name = sys.argv[1].strip('@')
    tweets = helpers.get_user_timeline(screen_name, 50)
    if tweets == None:
        print("Error")
        exit(2)

    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(tweet, "green"),score)
        elif score < 0.0:
            print(colored(tweet, "red"),score)
        else:
            print(colored(tweet, "yellow"),score)

if __name__ == "__main__":
    main()